### ISSUE TITLE
Thanks for porting!

### ISSUE THREAD

**Issue by EdenEast** [keifererikson/vscode-nightfox#1]
First off I would like to say thank you for taking on porting nightfox to vscode. I have had requests to port nightfox to vscode but did not want to write and maintain another repo. 

Also I ❤️ the icon design that you have made! I would like to ask your permission to use that as the icon for nightfox. Your design is much better then the one I made originally for nightfox.

Let me know if you need anything.

**Comment by keifererikson** [comment]
Hi @EdenEast!

Thanks for finding my repo, and commenting! I was hoping to have it a little more fleshed out before presenting it to you, but that's okay. 😛

I'm glad you like the logo! What would be the best way for me to send you the logo files?

Thanks again, and thanks for making an awesome theme! 🦊

**Comment by EdenEast** [comment]
For the logo files you could open a pr in nightfox with the files commited to the repo. I can use the ones commited there.
