### ISSUE TITLE
Other fox

### ISSUE THREAD

**Issue by kamalkech** [keifererikson/vscode-nightfox#2]
how cann config it  for dayfox - dawnfox - duskfox - nordfox - terafox - carbonfox ??

**Comment by ajorgensen** [comment]
I was able to hack together a script to generate, at least to my untrained eye, dark themes that look pretty close to the canonical  versions. I definitely think there is room for improvement here but hopefully this is a decent starting point. https://github.com/keifererikson/vscode-nightfox/pull/3

**Comment by z3ugma** [comment]
Now that #3 is merged, should just need @keifererikson to ship the latest release to the VSCode store

**Comment by keifererikson** [comment]
Appreciate your patience guys. I was kind of disconnected for a while there. It should be live now! 

@ajorgensen thanks for taking the time to put a script together to get the other themes generated!
